### ISSUE TITLE
[FEATURE] Update for Foundry v11

### ISSUE THREAD

**Issue by steveculshaw** [johnnolan/export-journal-html#110]
**Describe the new feature**
Update for Foundry v11

**Additional Information**
The current `module.json` has the compatibility maximum set to `10`

**Comment by steveculshaw** [comment]
Tried to install 0.5.2 but getting error ...

<img width="729" alt="image" src="https://github.com/johnnolan/export-journal-html/assets/64320/57d5e3aa-d5ac-4a04-9eb0-c2965dbd4627">

**Comment by steveculshaw** [comment]
@johnnolan Many thanks 

<img width="289" alt="image" src="https://github.com/johnnolan/export-journal-html/assets/64320/bbde4e6e-4e3a-46b9-a5c4-f873de7f9ee8">

**Comment by johnnolan** [comment]
No problem at all @steveculshaw , had a few issues with getting the release packaged, hence those lovely errors you got for a short time. Thanks for raising!

**Comment by steveculshaw** [comment]
Many thanks for sorting so promptly ... I mean getting a change in a few minutes is amazing !!!
