### ISSUE TITLE
Compatibility with Monk's Enhanced Journal?

### ISSUE THREAD

**Issue by myrduende** [johnnolan/export-journal-html#144]
Not sure if a bug or simply an incompatibility issue.  The print icon does not show up when using Monk's Enhanced Journal - whether in single entry, multiple entry or edit views.  System is PF1e v9.4.  Foundry is v10.291.   Export Journal v0.6.1.

![image](https://github.com/johnnolan/export-journal-html/assets/133538704/f51c29d1-cfba-42d4-8d73-406fd5d865c3)

![image](https://github.com/johnnolan/export-journal-html/assets/133538704/0c0cca4c-a754-4afc-a593-c9a41ffdba0e)

**Comment by DekuScrubs** [comment]
Doesn't show for me, but simply disabling it makes it work fine, then you just reenable it
