### ISSUE TITLE
Getting Blob error when hitting Print button

### ISSUE THREAD

**Issue by grimmash** [johnnolan/export-journal-html#21]
**Describe the bug**
When I click the print Icon on Win 10 in Foundry 10.291, PF 2e 4.5.1, windows directs me to select an app from the app store to open the blob. 

**To Reproduce**
1. Go to a Journal
2. Click on Print

Console Log error:
PrintButton.ts:17 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at PrintButton.ts:17
    at Array.filter (<anonymous>)
    at Function.<anonymous> (PrintButton.ts:17)
    at Generator.next (<anonymous>)
    at module.js:1
    at new Promise (<anonymous>)
    at u (module.js:1)
    at Function.Add (PrintButton.ts:9)
    at Object.<anonymous> (module.ts:20)
    at Generator.next (<anonymous>)

**screenshot of the output if any is generated**
![image](https://user-images.githubusercontent.com/58613668/212414545-7327e9dc-3754-4045-b7b8-987dc889cefb.png)

**A screenshot the the content in the Journal view**

**The HTML of the Journal causing issues**

**Comment by johnnolan** [comment]
Ah sorry, at the minute you have to use a browser for this to work, if you open a browser and log in locally (think a default install will be `http://localhost:30000/join` [localhost:3000](http://localhost:30000/join) and it will work from there.

Going to leave this open as a bug though and see if it is possible to make popups work of some kind in the Electron app. 

Hope that solves the problem for now!

**Comment by johnnolan** [comment]
Other module developers such as Popout also have the same problem, not able to open popouts from the standalone app. I have added a warning for now when using it to use a browser https://github.com/johnnolan/export-journal-html/releases/tag/0.5.2 but will keep looking for ways around it in the future

**Comment by grimmash** [comment]
Ha!  Okay, i will test in the client.  Totally forgot about that.
