### ISSUE TITLE
my tables become broken during export [BUG]

### ISSUE THREAD

**Issue by patrickmohrmann** [johnnolan/export-journal-html#41]
**Describe the bug**
when i transform the journal to pdf, the tables insid the journals become brocken

**To Reproduce**
1. import journal 
[fvtt-JournalEntry-altes-blut.zip](https://github.com/johnnolan/export-journal-html/files/10793921/fvtt-JournalEntry-altes-blut.zip)
2. select the multi page view
3. click the print button
4. check out the first table  and compare it to the journal.
5. See error

**screenshot of the output if any is generated**

**A screenshot the the content in the Journal view**
![image](https://user-images.githubusercontent.com/76265425/220358626-38b38c7f-ec75-49c8-bf58-84f18ae1d198.png)
![image](https://user-images.githubusercontent.com/76265425/220358701-fc5fb79f-a3a3-4dc1-a631-4eb0677eea8e.png)

**The HTML of the Journal causing issues**
[issue-html.zip](https://github.com/johnnolan/export-journal-html/files/10793965/issue-html.zip)

**Comment by patrickmohrmann** [comment]
Thank you for your support

**Comment by johnnolan** [comment]
Thanks for raising, having some troubles at home but will get to this asap for you :)

**Comment by johnnolan** [comment]
Initial looks are there is a missing </table> element that is causing the layout issue when the module is trying to render the page. Founddry seems to be handling this somehow better than the raw output.

I am just trying to install the system (which seems to not be working at the minute) and will try and reproduce to see what I may be missing on my side, but in the mean time if you fancy looking at the code of your Journal that may be the quickest fix.

Will report back here once I have the system installed and debugged it
